### PR TITLE
docs(manual): fix `--stream` typo

### PR DESCRIPTION
**Pull request by Vap0r1ze**
this fixes a small typo that had me confused about `--stream` initially

### CODE REVIEW

**Comment by wader** [comment]
LGTM, i wonder why the "end" array/object paths are skipped in the examples?
```
$ jq --stream -c <<< '[[],"a",["b"]]'
[[0],[]]
[[1],"a"]
[[2,0],"b"]
[[2,0]]
[[2]]
```

**Comment by Vap0r1ze** [comment]
Me as well, though I didn't question it much because it was just *new* info to me rather than *inaccurate* info :P

**Comment by itchyny** [comment]
Duplication of #1279, #2010.

**Comment by Vap0r1ze** [comment]
that pr is from 2019 and has merge conflicts, clearly dead i figured it would be better to just fix immediately since it is one byte

**Comment by Vap0r1ze** [comment]
please let me know if this isnt an easy merge

**Pull request closed without merging**
