### PR TITLE
mark functions which require 1.5

### PR DESCRIPTION
**Pull request by JuanCanham**
The online docs are the main source for a lot of people (e.g me) so merging this will prevent people (e.g me) banging their heads when the docs don't work.

### CODE REVIEW

**Comment by wtlangford** [comment]
Hey! You've started the process I've been putting off forever! The issue,
though, is that the changes need to be made to the .yml file and the script
to generate the html and man pages needs to be updated.

**Comment by pkoppstein** [comment]
In the interim, would it be possible to revert the online manual so that it is in-sync with jq 1.4?

**Comment by nicowilliams** [comment]
Thanks!

**Comment by JuanCanham** [comment]
@wtlangford, I was worried you might say that. As this temp fix will break as soon as you update the docs  I'll try and get it done this week (including Sunday).

**Comment by wtlangford** [comment]
In the meantime, @nicowilliams has taken your PR and merged it into a new
branch to use for the docs.

**Comment by pkoppstein** [comment]
It would be great if the patch (or patches) could correct the references to `split2`. They should all be changed to `splits` (as in "split-with-stream-orientation").  Thank you!

**Pull request merged**
