### PR TITLE
Revert "Disable appveyor build for now"

### PR DESCRIPTION
**Pull request by janschulz**
This reverts commit 0b8218515eabf1a967eba0dbcc7a0e5ae031a509.

There is a new oniguruma package which previously trashed the build.

### CODE REVIEW

**Comment by janschulz** [comment]
Lets see if it works...

**Comment by janschulz** [comment]
And it looks good: https://ci.appveyor.com/project/stedolan/jq/build/1.0.28/job/l5at1u4hxuviqmu5 :-)

**Comment by janschulz** [comment]
There are still a few failures, but these are masked by `|| cat log`, so it seems these are on purpose...

**Comment by jan-schulz-k24** [comment]
Any news on this?

**Comment by nicowilliams** [comment]
Thank you thank you!

**Pull request merged**
