### PR TITLE
Handle cut-off UTF-8 sequences when reading files

### LINKED ISSUE #1311: Broken cyrillic in string literals.
File example: [jq.txt](https://github.com/stedolan/jq/files/716344/jq.txt).
Command: `jq -n -f jq.txt`.

I expect that output contains equal strings under the paths `validation.rules.rule3.errorMessages.regexNotMatched` and `validation.rules.rule4.errorMessages.regexNotMatched`, but `rule3` contains altered 5th symbol (and it does not seem to be valid utf8 codepoint).

Similar replacements somewhere in first two words occure with modifications in the 7th line (marked with comment "magic line"), if a) remove comment (with space after comma), b) remove text except leading six spaces, c) remove all text, leaving blank line.

jq-1.5rc2-152-g0b82185 (and same errors with jq-1.5 from Centos 7 repository).

Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

--
Alexey Golovko, a.golovko1@tinkoff.ru

### PR DESCRIPTION
**Pull request by wtlangford**
Read additional bytes from the file to complete the UTF-8 sequence so the bytes
in it don't get converted to U+FFFD replacement characters.

Things to note:
- Added a new test to the Makefile, as the jq testing framework uses a different mechanism to run tests
- Added a new function to `jv_unicode.c`: `jv_utf8_backtrack`, which backtracks in a string to find the beginning of the final codepoint and also returns the number of bytes missing in that codepoint.
- `jv_load_file` now checks whether the final utf-8 sequence is complete, and pulls the appropriate number of bytes to complete it from the source file in the (unlikely) case that it is not.

This changes the way we load jq programs into memory, so please bang on it for a bit and make sure I didn't introduce any new bugs.  All of the tests pass for it, but we didn't have any tests that were very long in the first place.  (This is doubly problematic, since the test code caps lines to 4096 bytes anyways...)

Fixes #1311

### CODE REVIEW

**Comment by nicowilliams** [comment]
Nice find.  I'll review tomorrow.

**Comment by nicowilliams** [comment]
This is beautiful.  LGTM.

**Comment by wtlangford** [comment]
If we're happy with this, then I'll merge it?

**Comment by pkoppstein** [comment]
@wtlangford - The sooner it's merged the better as it will result in more "in situ" testing being done. I think @nicowilliams's LGTM can be taken as "Yes" if not "Please!" :-)

**Comment by nicowilliams** [comment]
@wtlangford Do please rebase and push it!

**Comment by wtlangford** [comment]
Merging despite appveyor.

**Pull request merged**
