### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by netei**

### CODE REVIEW

**Comment by dtolnay** [comment]
I think the original is correct. The wording means "does not output anything, not even an error." I don't think the new wording makes this clearer.

**Comment by nicowilliams** [comment]
The original wording means "it outputs nothing (not even an error) when `.` is neither an object nor an array", and the proposed new wording means "it does not output an error when `.` is neither an object nor an array" but says nothing about any values that might be output in that case except implicitly by reference to "`like `.foo`".  So it's not really a change at all.

**Comment by netei** [comment]
I think the current wording is still misleading. It should probably be : 

> Just like `.foo`, but does not output an error when `.` is not an array or an object.

Before it was : 

> Just like `.foo`, but does not output even an error when `.` is not an array or an object.

The "even" is unecessary here.

**Comment by pkoppstein** [comment]
@netei - Evidently you are misunderstanding something. The "even" is not only correct, but essential to capture the intended meaning.

**Comment by nicowilliams** [comment]
Just like .foo, but does not output an error when . is not an array or an object.

Does work.  It's true that the "even" is redundant when one knows how `.foo` works.  Still, the "even" isn't wrong.

**Pull request closed without merging**
