### PR TITLE
Change usage formatting

### PR DESCRIPTION
**Pull request by sparrc**
First off, thanks for making `jq`, it's an awesome tool!!

I've always found the usage text to be a little difficult to grok. This is obviously a matter of opinion, but this PR would change the text from looking like this:

```
$ jq
jq - commandline JSON processor [version 1.5]
Usage: jq [options] <jq filter> [file...]

	jq is a tool for processing JSON inputs, applying the
	given filter to its JSON text inputs and producing the
	filter's results as JSON on standard output.
	The simplest filter is ., which is the identity filter,
	copying jq's input to its output unmodified (except for
	formatting).
	For more advanced filters see the jq(1) manpage ("man jq")
	and/or https://stedolan.github.io/jq

	Some of the options include:
	 -c		compact instead of pretty-printed output;
	 -n		use `null` as the single input value;
	 -e		set the exit status code based on the output;
	 -s		read (slurp) all inputs into an array; apply filter to it;
	 -r		output raw strings, not JSON texts;
	 -R		read raw strings, not JSON texts;
	 -C		colorize JSON;
	 -M		monochrome (don't colorize JSON);
	 -S		sort keys of objects on output;
	 --tab	use tabs for indentation;
	 --arg a v	set variable $a to value <v>;
	 --argjson a v	set variable $a to JSON value <v>;
	 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
	See the manpage for more options.
```

to this:

```
$ jq
jq - commandline JSON processor [version 1.5rc2-129-g22f5c97]

Usage:

	jq [options] <jq filter> [file...]

jq is a tool for processing JSON inputs, applying the given filter to
its JSON text inputs and producing the filter's results as JSON on
standard output.

The simplest filter is ., which copies jq's input to its output
unmodified (except for formatting).

For more advanced filters see the jq(1) manpage ("man jq")
and/or https://stedolan.github.io/jq

Example:

	$ echo '{"foo": 0}' | jq .
	{
		"foo": 0
	}

Some of the options include:
  -c               compact instead of pretty-printed output;
  -n               use `null` as the single input value;
  -e               set the exit status code based on the output;
  -s               read (slurp) all inputs into an array; apply filter to it;
  -r               output raw strings, not JSON texts;
  -R               read raw strings, not JSON texts;
  -C               colorize JSON;
  -M               monochrome (don't colorize JSON);
  -S               sort keys of objects on output;
  --tab            use tabs for indentation;
  --arg a v        set variable $a to value <v>;
  --argjson a v    set variable $a to JSON value <v>;
  --slurpfile a f  set variable $a to an array of JSON texts read from <f>;

See the manpage for more options.
```

### CODE REVIEW

**Comment by pkoppstein** [comment]
This would be a good time and place to be more forthcoming about jq's current proclivities to take liberties with some numbers; perhaps:

(except for formatting) -> (except for formatting and the handling of certain numbers).

**Comment by nicowilliams** [comment]
Thanks.  I'll merge this tomorrow.  I may add something about numbers being IEEE754.

**Comment by nicowilliams** [comment]
Cherry-picked as 6d76cd0.

**Comment by nicowilliams** [comment]
Thanks!

**Pull request closed without merging**
