### PR TITLE
Fix multiple string multiplication

### LINKED ISSUE #2117: String multiplication produces unexpected result
**Describe the bug**
Multiple string multiplication produces unexpected result on mac osx

**To Reproduce**
`echo 0 | jq '"x" * 2 * 36'`
output: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\u0004\u0000"

**Expected behavior**
output: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

**Environment:**
 - OS and Version: macos 10.15.4
 - jq version: 1.6

**Additional context**
Tried on centos, no such problem

### PR DESCRIPTION
**Pull request by itchyny**
This pull request fixes #2117. And maybe #2115 as well (I can't confirm yet).

### CODE REVIEW

**Comment by whentze** [comment]
I just tried the reproducing example from #2115 against this branch and it doesn't crash (and prints the correct result). Sanitizers and valgrind are looking clean too.

**Comment by wtlangford** [comment]
Good find! I'll suggest a slightly more efficient solution:
```c
jv res = jv_null();
int n = jv_number_value(num);
if (n > 0) {
  size_t alen = jv_string_length_bytes(jv_copy(str));
  res = jv_string_empty(alen * n);

  for (; n > 0; n--) {
    res = jv_string_append_buf(res, jv_string_value(str), alen);
  }
}
jv_free(str);
jv_free(num);
return res;
```

**Comment by itchyny** [comment]
@wtlangford I update the patch, thanks. But considering the performance here seriously, we should reduce the number of `jvp_utf8_is_valid` checks.

**Comment by wtlangford** [comment]
> @wtlangford I update the patch, thanks. But considering the performance here seriously, we should reduce the number of `jvp_utf8_is_valid` checks.

Agreed, we should- but for now, I think this is good. Thanks for tracking this down!

**Comment by itchyny** [comment]
I noticed that `0.5 * "abc"` is changed by this pull request. Should we keep the original behavior?

**Comment by wtlangford** [comment]
Yes, we definitely should

**Pull request merged**
