### PR TITLE
byteslength builtin: count UTF8-encoded bytes

### LINKED ISSUE #941: Count length in bytes in UTF8 (or arbitrary encoding)
I was hoping to use `jq` to transform some JSON records into [redis](http://redis.io) [`APPEND`](redis.io/commands/append) commands (to produce json-seq entries), via its [`redis-cli --pipe` mass-insertion protocol](redis.io/topics/mass-insert). This involves formatting a string in which each argument is prefixed by its length in bytes. `length`, however, only counts the number of Unicode characters. Seeing as strings are output in UTF8, a function to calculate the number of bytes in UTF8 would be valuable so I can construct a redis command as follows:
```
jq -j '(tostring | "\u001e\(.)\n") as $blob | "*3\r\n$6\r\nAPPEND\r\n$\(.key | byteslength)\r\n\(.key)\r\n$\($blob | byteslength)\r\n\($blob)\r\n"'
```

### PR DESCRIPTION
**Pull request by jnothman**
Fixes #941 using a builtin.

### CODE REVIEW

**Comment by wtlangford** [comment]
I have concerns about coercing jvs to a string in that builtin. I think I'd
rather it be defined only on strings, unless someone can convince me
otherwise?

**Comment by jnothman** [comment]
I'm somewhat ambivalent about it. There seems to be more implicit coercion/polymorphism in jq than I'm used to in other frameworks so I included it as something that might occasionally be useful.

**Comment by wtlangford** [comment]
That's fair. We just want to be certain that the polymorphic behavior is
expected and reasonable. I'm on my phone, so I'm not going to dig in and
look at the moment. I'll take a look later today.

**Comment by nicowilliams** [comment]
Comments:

 - Don't coerce values to strings.  Instead use the `type_error()` function to raise an error when the input is not a string.

 - Such a builtin should be named `utf8bytelength` or similar.  The reason is that JSON strings' encoding is notionally not specified -- JSON _texts_ may be encoded in UTF-8, UTF-16, and UTF-32, but that's _texts_, not _strings_.  Therefore a builtin that counts string bytes should specify which UTF to use.

**Comment by nicowilliams** [comment]
Also: thanks!  This will be a useful builtin, I believe.  Thank you for taking the time to learn how to do this.  If you'd like I could make the changes I propose and push it (I tend to do this for PRs to save the submitter the trouble of a back-n-forth).

**Comment by jnothman** [comment]
> Therefore a builtin that counts string bytes should specify which UTF to use.

Yes, I'd originally anticipated this, but I had no intention to add other encodings if `jq` only produced output in UTF8. One could even add encoding as an optional parameter to `length`. Should we really support encodings other than UTF8 initially?

**Comment by wtlangford** [comment]
I'd say no since jq doesn't output the other encodings, which means you'd
have to do the math manually.

**Comment by nicowilliams** [comment]
We might never support other encodings, but that doesn't mean that being
able to count code units and bytes for them wouldn't be useful.

**Comment by nicowilliams** [comment]
Alright, so, unless there are any further objections, I've a rebased version of this with a builtin name of `utf8bytelength` that only accepts string-type inputs.  See the `utf8bytelength` branch of my clone.

**Comment by dtolnay** [comment]
@nicowilliams since you know the input is a string, you no longer need to call f_tostring.

**Comment by nicowilliams** [comment]
@dtolnay Ah, thanks, good catch!  (I'd meant to remove it, but forgot after adding the type check).

**Comment by pkoppstein** [comment]
@nicowilliams - The example is one-third broken as the input must now be a string.

**Comment by nicowilliams** [comment]
@dtolnay Huh, mantests pass.  `rake mantests` is not producing tests out of the example for `utf8bytelength`.  Investigating...

**Comment by nicowilliams** [comment]
Oh, duh.  Wrong yml file.

**Comment by nicowilliams** [comment]
@dtolnay OK, that's fixed now.

**Comment by jnothman** [comment]
Sorry I've not got back to this, but (without code review) it's notionally fine by me.

**Comment by dtolnay** [comment]
Looks good.

**Comment by nicowilliams** [comment]
Closed with 83e8ec5.  Thanks!

**Comment by jnothman** [comment]
Thank you!!

**Pull request closed without merging**
