### PR TITLE
array and object destructuring (fix #533)

### LINKED ISSUE #533: `. as [$foo, $bar, $baz]` array destructuring?

### PR DESCRIPTION
**Pull request by dtolnay**
`. as [$i, $j, $k] | ...`
`. as {a: $i, b: $j} | ...`
`. as [[[$i]], {a: $j}] | ...`

### CODE REVIEW

**Comment by dtolnay** [comment]
I have not changed reduce and foreach in this commit because first I want to better understand issue #618 and the need for DUPN.

**Comment by nicowilliams** [comment]
@dtolnay  About `DUPN`, take a look at `stack_pop()`: it does a `jv_copy()` if `!stack_pop_will_free(...)`, which is when the value is not at the top of the stack, which is when we've pushed a fork point, say.  But we know the value won't be used again here (since we're generating the `DUPN` or `LOADVN`), so we just replace the value with a `null` instead of incrementing its reference count.  Perhaps I should instead have written a check that the only thing between the value and the top is a fork point, and for all I remember right now maybe I tried that and decided for `DUPN` instead for some reason I don't recall.  I appreciate more minds looking at this, as this is tricky business!

**Comment by nicowilliams** [comment]
Interesting thought though to allow destructuring in the `reduce`/`foreach` syntax...  I like it.

**Comment by dtolnay** [comment]
Addressed feedback (added comment for block_bind_subblock and renamed prior/pattern to left/curr) and finished reduce and foreach.

**Comment by pkoppstein** [comment]
@dtolnay - This is great stuff!  It is especially helpful, for example, when writing 0-arity functions that stuff a lot of baggage into the "input".  One thing that is perhaps not so obvious is that the match-making is quite liberal.  Since this is evidently intended, I think it would be a good idea to signal as much e.g. by adding a test case like this:
```
reduce [[1,2,10], [3,4,10]][] as [$i,$j] (0; . + $i * $j)
null
14
```


@nicowilliams - Any chance this can make it into 1.5rc2?

**Comment by dtolnay** [comment]
It is intended. `. as [$i, $j]` should be shorthand for `.[0] as $i | .[1] as $j`, and similarly for objects. I have added your suggested test case. I had this similar one but not for reduce: `[[1], [1, 2, 3]] as [$a, $b] | [$b, $a]`.

**Comment by nicowilliams** [comment]
@pkoppstein  Right, the destructuring patterns need not completely match the input -- that would be obnoxious, though perhaps an option for that would be nice (but let's leave that to another day).  Also, array destructuring has to be anchored on the left or right end of the array given this, and the left it is.  Finally, it might be nice to be able to bind a `$varnme` to "the rest of the array", and or to destructure out of order.  I'm thinking of something like `. as [1->$second, 0->first, rest->$rest] | ...`, but nothing in @dtolnay's work precludes us adding that later, so I think we're good (not that you're suggesting that we do this now).  But you're right that the docs need a clarification.

**Comment by nicowilliams** [comment]
I've pushed @dtolnay's commit with one change: I git added the `parser.c` generated by bison.

I also pushed a clarification to the manual about array destructuring patterns.

**Comment by nicowilliams** [comment]
Closed with d3343d5 (cherry-picked from c22543a, with an updated `parser.c` squashed in).

Thanks!

**Comment by nicowilliams** [comment]
@dtolnay I finally cleared everything up (I hope) w.r.t. #618.  I may push a better fix for that.

**Comment by nicowilliams** [comment]
Another destructuring feature that might be nice would be syntax like this:

    # for each key/value pair in ., produce . and
    # assign the key to $k and the value to $v
    . as .{$k: $v}

and

    # for each value in . (array or object), produce . and
    # assign the value to $v
    . as .[$v]

Then one could write expressions like:

    . as .objects[].{object: $obj}.relations[].{relation: $rel} | ...

which is useful when dealing with perverse :) schemas like

    {
      "objects": [
        {
          "object": {
            ...,
            "relations": [
              {
                "relation": { ... }
              },
              ...
            ]
          }
        },
        ...
      ]
    }

OK, this is me casting about for a hammer for that ugly nail.  I really do have such JSON to work with, so I often write this sort of expression:

    .objects[].object as $o | .relations[].relation as $r | ... do things with $o and $r ...

This is probably a terrible idea, so don't go off and implement.  It should stew for a while.

**Pull request closed without merging**
