### PR TITLE
simplify implementation of bsearch to use "until" and avoid "last"; tested

### PR DESCRIPTION
**Pull request by pkoppstein**

### CODE REVIEW

**Comment by dtolnay** [comment]
@nicowilliams do you know what this was waiting on?

**Comment by nicowilliams** [comment]
Don't recall.

**Comment by pkoppstein** [comment]
@dtolnay - Thanks for reviewing this and other half-forgotten PRs (and for all the other great things you've been doing).  The first version of bsearch was written before "until" had been added as a builtin.  In fact, "until" was motivated by the silliness of the last(while(_)) pattern.  In short, please proceed!

**Comment by wtlangford** [comment]
LGTM, I'll go ahead and merge this.

**Pull request merged**
