### PR TITLE
Change backticks to the more legible $()

### PR DESCRIPTION
**Pull request by davidfetter**

### CODE REVIEW

**Comment by davidfetter** [comment]
Bump :)

**Comment by nicowilliams** [comment]
@davidfetter Does the OS X sh support this?

**Comment by pkoppstein** [comment]
@nicowilliams -

```
sh-3.2$ /usr/bin/sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1611
sh-3.2$ sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
sh-3.2$ echo $(echo abc)
abc
sh-3.2$ 
```

**Comment by nicowilliams** [comment]
Thanks!

**Pull request merged**
