### PR TITLE
Build 32bit and run tests on appveyor

### PR DESCRIPTION
**Pull request by JanSchulz**
This is a addon to https://github.com/stedolan/jq/pull/1074 (including that PR), which adds

* 32bit builds (currently failing)
* html help files from the man pages
* run the test suite (currently failing)

64bit build logs: https://ci.appveyor.com/project/JanSchulz/jq/build/job/5lca2kfdijltolej
32bit build logs: https://ci.appveyor.com/project/JanSchulz/jq/build/job/4jolgdm69b7qfofq

### CODE REVIEW

**Comment by JanSchulz** [comment]
Windows 32bit build failure:

```
CC       src/jv_file.lo
  CC       src/jv_parse.lo
  CC       src/jv_print.lo
  CC       src/jv_unicode.lo
  CC       src/linker.lo
src/linker.c: In function 'path_is_relative':
src/linker.c:32:13: warning: implicit declaration of function 'PathIsRelativeA' [-Wimplicit-function-declaration]
   int res = PathIsRelativeA(s);
             ^
  CC       src/locfile.lo
  CC       src/util.lo
  CC       src/lexer.lo
  CC       src/parser.lo
  CCLD     libjq.la
libtool: warning: undefined symbols not allowed in x86_64-pc-mingw32 shared libraries; building static only
  CC       src/main.o
  CCLD     jq.exe
./.libs/libjq.a(linker.o): In function `path_is_relative':
C:\projects\jq/src/linker.c:32: undefined reference to `PathIsRelativeA'
collect2.exe: error: ld returned 1 exit status
Makefile:893: recipe for target 'jq.exe' failed
make[1]: *** [jq.exe] Error 1
make[1]: Leaving directory '/c/projects/jq'
Makefile:734: recipe for target 'all' failed
```

**Comment by nicowilliams** [comment]
I don't get that.   One of my commits makes `src/linker.c` `#include <shlwapi.h>`, which makes that warning/error go away.

**Comment by nicowilliams** [comment]
Ah, you're using origin/master as the base.  Got it.

**Comment by nicowilliams** [comment]
Thanks!  I'll merge after merging my fixes for Windows.

**Comment by nicowilliams** [comment]
Cherry-picked onto master.  Thanks!

**Pull request closed without merging**
