### PR TITLE
Added `is{scalar,value,..}`. Fixes leaf_paths bug.

### PR DESCRIPTION
**Pull request by alex-ozdemir**
Now paths to `false` leaves are correctly returned.
Added the new test functions to the docs.

### CODE REVIEW

**Comment by alex-ozdemir** [comment]
This is a partial solution to #1163.

**Comment by slapresta** [comment]
I proposed something very similar a long time ago. I like it! I find myself using `type == "array"` more often than `arrays`.

**Comment by alex-ozdemir** [comment]
Okay, paths to `null` handled by fixing `paths`. The fix uses an alternative behavior for recurse. I chose not to include this new behavior in the stdlib, as having two floating around would probably just confuse people.

This PR now completely closes #1163.

**Comment by nicowilliams** [comment]
Thanks!  I'll review.

**Comment by alex-ozdemir** [comment]
Paging @nicowilliams 😄

**Pull request closed without merging**
