### PR TITLE
readability

### PR DESCRIPTION
**Pull request by isomorphisms**
Easier to read dashes than hyphens imho.

### CODE REVIEW

**Comment by joelpurra** [comment]
@isomorphisms: I disagree. Spaces mean the words are separate.

**Comment by wtlangford** [comment]
@joelpurra - The PR uses em dashes instead of hypens, so they're longer and do _technically_ have different meaning, though I think many(most?) people won't pick up on the difference without it being explicitly pointed out.

I tried out this version of the docs, and I do like the em dashes, personally.  I'm going to go ahead and merge this in.

**Comment by joelpurra** [comment]
@isomorphisms: didn't see that they're em dashes.

@wtlangford: still prefer spaces around em dashes.

Oh well.

**Comment by wtlangford** [comment]
@joelpurra:  I played around with the different combinations (em dash, hyphen)x(spaces, none) and decided I liked (em dash,spaces) best.  Do not fear, though.  I'm looking towards a rebuild of the docs to coincide with the 1.5 release (which may mean they get removed again, though it is unlikely). Basically, I want whatever we end up doing wrt packages/modules/etc to end up in the documentation for it.  I'm also going to add version info to core functions/syntax (introduced in, deprecated/removed in, semantics/behavior changed in, etc).  This should also help insulate against another leakage of future functionality into the current release docs.  #630 should have the current status on that, though I haven't really been up to date in there.

The other major goal with that is to try to slim down the amount of dependencies on docs building.  Most of those exist to support serving the docs (`rake serve` in the docs folder).  I think there's a way to allow manpage building without needing the serving dependencies, but I'll have to play with it.

**Comment by joelpurra** [comment]
@wtlangford: sounds good! I'm pushing for #558, to have smaller releases more often, in a structured way. It could/would/should also mean more active use of marking functionality as introduced, deprecated etcetera.

**Pull request merged**
