### PR TITLE
get Travis CI working

### PR DESCRIPTION
**Pull request by dtolnay**
Here is the build of the commit in the PR: https://travis-ci.org/dtolnay/jq/builds/68582926

### CODE REVIEW

**Comment by dtolnay** [comment]
I put libonig-dev under packages for the apt addon to install, but it still needs to be whitelisted by travis. I filed a whitelist request here: https://github.com/travis-ci/travis-ci/issues/4123. Until then I am building against artifacts from debian. Similarly for bison - although it is whitelisted, the version in the repo is 2.5 and we need 3.0.

**Comment by nicowilliams** [comment]
Did you mean to keep the `env PAGER=less ` bit?  Does valgrind use `$PAGER`?

**Comment by nicowilliams** [comment]
Pushed as 815b4c9.  Thanks!

**Comment by nicowilliams** [comment]
Oh, no!  You did want to set the `PAGER` because a mantest wants it.  *sigh*

**Comment by nicowilliams** [comment]
Ugh, my fix commit should have mentioned that the braino was mine, not yours.

**Comment by dtolnay** [comment]
Thanks for adding the comment. I'll take the blame for not having one in the first place.

**Pull request closed without merging**
