### PR TITLE
Fix #817

### LINKED ISSUE #817: incorrect handling of ./ in search path
Currently on master:

    jq$ ./jq -L tests/modules -n 'import "test_bind_order" as check; check::check'
    true
    jq$ ./jq -L ./tests/modules -n 'import "test_bind_order" as check; check::check'
    jq: error: module not found: test_bind_order0

    jq: 1 compile error

### PR DESCRIPTION
**Pull request by nicowilliams**
These two commits cleanup how we expand module search path elements.  Please review.

### CODE REVIEW

**Comment by nicowilliams** [comment]
We could make assignment of PR to someone other than its author be a poke to another collaborator to do a code review.  Should we?

**Comment by nicowilliams** [comment]
@joelpurra Can you be more specific?

**Comment by nicowilliams** [comment]
I do need to add a test...

**Comment by dtolnay** [comment]
Looks good to me. Seems to work correctly but I only tested on Linux. Please add a test for the case in the bug report.

**Comment by dtolnay** [comment]
> We could make assignment of PR to someone other than its author be a poke to another collaborator to do a code review. Should we?

I don't think we need to assign PRs. The collaborators get emails about them so we know when one is waiting for a code review. After some reasonable amount of time (like 48 hours) a polite @mention should be enough.

**Comment by nicowilliams** [comment]
@joelpurra ping.  Can you be more specific?

**Comment by joelpurra** [comment]
@nicowilliams wrote:
> @joelpurra Can you be more specific?

@nicowilliams wrote:
> @joelpurra ping. Can you be more specific?

That was a comment on a code line; seems they're pulled in to the issue comment stream now; think they should be differentiated a bit more from ordinary comments.
https://github.com/nicowilliams/jq/commit/1d77ada1e6e5dbbe83bc29ba07c9440e57534eb6#diff-8950c7cecbfb6fbbee14e43bffd28221R199

Looking at the diff only, it seemed weird to use `err` when it's invalid, and not use it when it's valid.

**Comment by dtolnay** [comment]
There is a type of jv called JV_KIND_INVALID which wraps an error message. The check for `!jv_is_valid(err)` is checking whether `err` is this type of jv.

I rebased these as 10df52e 5d08d54 b119853.

**Comment by dtolnay** [comment]
Cherry-picked to jq-1.5-branch as 66f7ce5 0683002 b60c9eb.

**Comment by joelpurra** [comment]
@dgryski: alright, thanks!

**Pull request closed without merging**
