### PR TITLE
Implemented contains operator

### PR DESCRIPTION
**Pull request by stroan**
The expression 'a contains b' will produce true if b is completely contained within a. 
- A string B is contained in a string A is B is a substring of A. 
- An array B is contained in an array A if all elements in B are contained in some element in A. 
- An object B is contained in  object A if all of the values in B are contained in the value in A with the same key. 
- All other types are assumed to be contained in each other if they are equal.

### CODE REVIEW

**Comment by dsikawat** [comment]
`$ jq '.[]|select(.key1|contains("bar")).key2' foo.json`
`jq: error (at foo.json:0): null (null) and string ("bar") cannot have their containment checked`

I'd expect the item with `key1=null` to return false and not get selected. Is contains not the right operator to use in this case?

**Comment by pkoppstein** [comment]
Since you haven't shown the contents of foo.json it's difficult to be sure, but it looks like you might want to use the postfix "?" operator:

```
$ jq '.[]|select(.key1|contains("bar")).key2' <<< '[{"key1":0}]'
jq: error (at <stdin>:1): number (0) and string ("bar") cannot have their containment checked

$ jq '.[]|select(.key1|contains("bar")?).key2' <<< '[{"key1":0}]'
$
```

**Comment by dsikawat** [comment]
This worked. Thanks.

**Comment by sakshan** [comment]
Do we have a keyword to match only if exact string? contains is matching if it has partial match.

**Pull request merged**
